### ISSUE TITLE
Draw the broken <pash> when run a `.open`  immediately after `.componentDidMount`.

### ISSUE THREAD

**Issue by 59naga** [bokuweb/react-elastic-modal#19]
![2016-03-11 14 51 00](https://cloud.githubusercontent.com/assets/1548478/13695396/91ab7bc2-e7a1-11e5-9335-26d5babe8240.gif)

[react-localstorage](https://github.com/STRML/react-localstorage)などを利用して、テストが意図しないタイミングでopenを実行する（`componentDidMount`直後にopenを実行させる）と、壊れた`<path>`を描写します。
また、初期値として`<ElasticModal isOpen={true}>`のように、初めから開いた状態にしたい初場合、その初期値が無視されます（`componentWillReceiveProps`が実行されないため）。

期待した結果は、ElasticModalがはじめから開いた状態で描写されるか、`.open`が実行され、画面を開いてすぐにElasticModalがアニメーションを開始することでした。

**Comment by bokuweb** [comment]
@59naga ありがとうございます！！修正します！！

**Comment by 59naga** [comment]
あ、PR投げます

**Comment by bokuweb** [comment]
@59naga ありがとうございます！！！！！！
